export enum SQSEvent {
  CREATE_DISTRIBUTOR_ORDER = 'CREATE_DISTRIBUTOR_ORDER',
  EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION',
  JOB_CARD = 'JOB_CARD',
  INVOICE = 'INVOICE',
  NOTIFICATION = 'NOTIFICATION',
  NEW_INVOICE = 'NEW_INVOICE'
}
