import { ACL } from '../enum/rbac.enum';

/* eslint-disable */
export const RBAC_MAP: any = {
  admin: [
    ACL.STORE_CREATE,
    ACL.STORE_GET_ALL,
    ACL.STORE_GET_SINGLE,
    ACL.CUSTOMER_GET_ALL,
    ACL.NOTIFICATION_SEND,
    ACL.ADVERTISEMENT_CREATE,
    ACL.ADVERTISEMENT_GET_CUSTOMER,
    ACL.ADD_VEHICLE,
    ACL.ADMIN_USER_CREATE
  ],
  store_owner: [
    ACL.STORE_CREATE,
    ACL.STORE_GET_OWNER,
    ACL.STORE_GET_SINGLE,
    ACL.FILE_UPLOAD,
    ACL.NOTIFICATION_SEND,
    ACL.ADVERTISEMENT_GET_CUSTOMER,
    ACL.ADD_VEHICLE
  ],
  user: [
    ACL.STORE_GET_ALL,
    ACL.STORE_REVIEW_CREATE,
    ACL.STORE_GET_SINGLE,
    ACL.CUSTOMER_CREATE,
    ACL.FILE_UPLOAD,
    ACL.ADVERTISEMENT_GET_CUSTOMER,
    ACL.ADD_VEHICLE
  ]
};
